### ISSUE TITLE
[feature]: Add Metrics exporter

### ISSUE THREAD

**Issue by destrex271** [destrex271/postgresexporter#1]

**Comment by rukins** [comment]
Hi @destrex271, thank you for your contribution! I am ready to implement metrics exporter, as it is needed for my company's project.
In addition, we are exploring the possibility of becoming a sponsor

**Comment by destrex271** [comment]
> Hi @destrex271, thank you for your contribution! I am ready to implement metrics exporter, as it is needed for my company's project.
> In addition, we are exploring the possibility of becoming a sponsor

Awesome. Thanks a lot for picking it up!
Would be great if we can get this merged in the official otel exporters.

I'll be happy to help out with pr reviews for this

**Comment by clarencebishop** [comment]
Hi, what is the status if the metrics exporter. I am needing this capability so that I can use PostgresSQL as my backend for my generated metrics.

**Comment by rukins** [comment]
Hi! It's implemented, just opened PR #2, please consider that it's still under development and may contain some bugs. we are testing it ourselves right now

**Comment by clarencebishop** [comment]
How do I access your  Postgress exporter under development in my local environment to play around with exporting metrics to a local Postgres database? What is the name of the Python package I need to include in my code? Sorry if these are simple answers but I am new to this. Thanks in advance for your help.

**Comment by destrex271** [comment]
> Hi! It's implemented, just opened PR [#2](https://github.com/destrex271/postgresexporter/pull/2), please consider that it's still under development and may contain some bugs. we are testing it ourselves right now. [@destrex271](https://github.com/destrex271) your review of the PR would be helpful

Suew, I'll get to it asap

**Comment by destrex271** [comment]
> How do I access your Postgress exporter under development in my local environment to play around with exporting metrics to a local Postgres database? What is the name of the Python package I need to include in my code? Sorry if these are simple answers but I am new to this. Thanks in advance for your help.

Hi, we don't have any python package for this exporter yet, for dev build purposes we follow the official OTEL guide to add new custom exporters using yaml config.
I'll update the documentation asap

**Comment by rukins** [comment]
> How do I access your Postgress exporter under development in my local environment to play around with exporting metrics to a local Postgres database? What is the name of the Python package I need to include in my code? Sorry if these are simple answers but I am new to this. Thanks in advance for your help.

@clarencebishop , if you mean how to create and expose metrics in your Python app, then you should use otel API and SDK (https://opentelemetry.io/docs/languages/python/).
But to use this postgres exporter (before it's merged into official repo), you can create your custom collector. Follow the step on https://opentelemetry.io/docs/collector/custom-collector/
Also here is example of configuration - https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/otelcontribcol

And

**Comment by rukins** [comment]
@clarencebishop , if you mean how to create and expose metrics in your Python app, then you should use otel API and SDK (https://opentelemetry.io/docs/languages/python/).

But to use this postgres exporter (before it's merged into official repo), you can create your custom collector. Follow the steps on https://opentelemetry.io/docs/collector/custom-collector/
Also here is example of configuration - https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/otelcontribcol

Your `builder-config.yaml` file should look similar to 

```yaml
dist:
  name: otellocalcol
  description: OpenTelemetry Collector Local for tests.
  version: 1.0.0
  output_path: ./cmd/otellocalcol

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.122.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.122.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.122.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.122.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.122.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.122.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.122.0
  - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.122.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.122.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.122.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.122.0

  - gomod: github.com/destrex271/postgresexporter v0.122.0
    path: "./exporter/postgresexporter" # if you have repo locally

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.28.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.28.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.28.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.28.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.28.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.122.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckv2extension v0.122.0

````

**Comment by destrex271** [comment]
> @clarencebishop , if you mean how to create and expose metrics in your Python app, then you should use otel API and SDK (https://opentelemetry.io/docs/languages/python/).
> 
> But to use this postgres exporter (before it's merged into official repo), you can create your custom collector. Follow the steps on https://opentelemetry.io/docs/collector/custom-collector/
> Also here is example of configuration - https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/otelcontribcol
> 
> Your `builder-config.yaml` file should look similar to 
> 
> ```yaml
> dist:
>   name: otellocalcol
>   description: OpenTelemetry Collector Local for tests.
>   version: 1.0.0
>   output_path: ./cmd/otellocalcol
> 
> receivers:
>   - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.122.0
>   - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.122.0
>   - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.122.0
>   - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.122.0
> 
> processors:
>   - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.122.0
>   - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.122.0
> 
> exporters:
>   - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.122.0
>   - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.122.0
>   - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.122.0
>   - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.122.0
>   - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.122.0
> 
>   - gomod: github.com/destrex271/postgresexporter v0.122.0
>     path: "./exporter/postgresexporter" # if you have repo locally
> 
> providers:
>   - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.28.0
>   - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.28.0
>   - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.28.0
>   - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.28.0
>   - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.28.0
> 
> extensions:
>   - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.122.0
>   - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckv2extension v0.122.0
> 
> ````
> 
> 

Thanks for adding it here! We should definitely move this to the readme of the project. I'll take care of that for now.

PS: I'll try to complete the review for this PR by Saturday and hopefully we can get it merged by Monday

**Comment by rukins** [comment]
@destrex271 thanks!

**Comment by clarencebishop** [comment]
Hi. I am getting the following error when I use ocb to build my custom collector with your postgres exporter:

exit status 1, error message: go: downloading github.com/destrex271/postgresexporter v0.122.0
go: github.com/destrex271/postgresexporter@v0.122.0: reading github.com/destrex271/postgresexporter/go.mod at revision v0.122.0: unknown revision v0.122.0

**Comment by rukins** [comment]
> Hi. I am getting the following error when I use ocb to build my custom collector with your postgres exporter:
> 
> exit status 1, error message: go: downloading github.com/destrex271/postgresexporter v0.122.0 go: github.com/destrex271/postgresexporter@v0.122.0: reading github.com/destrex271/postgresexporter/go.mod at revision v0.122.0: unknown revision v0.122.0

sorry, I was wrong, you should specify `main` instead of `v0.122.0`, fixed it.
But, before the metrics exporter merged into `main`, you can use it only by downloading the changes locally and setting `path`

**Comment by clarencebishop** [comment]
Hi. I have sucessfully built the postgres exporter but I am getting the following error when my application creates a metric that the collector receives:

go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewQueueSender.func1
	go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queue_sender.go:56
go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*disabledBatcher[...]).Consume
	go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queuebatch/disabled_batcher.go:22
go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*asyncQueue[...]).Start.func1
	go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queuebatch/async_queue.go:47
2025-04-18T10:45:21.860-0500	info	Metrics	{"resource metrics": 1, "metrics": 4, "data points": 6}
2025-04-18T10:45:21.878-0500	error	internal/queue_sender.go:56	Exporting failed. Dropping data.	{"error": "insert histogram metrics failed: ERROR: improper qualified name (too many dotted names): otel.http.server.duration (SQLSTATE 42601)", "dropped_items": 6}

**Comment by destrex271** [comment]
> Hi. I have sucessfully built the postgres exporter but I am getting the following error when my application creates a metric that the collector receives:
> 
> go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewQueueSender.func1
> 	go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queue_sender.go:56
> go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*disabledBatcher[...]).Consume
> 	go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queuebatch/disabled_batcher.go:22
> go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*asyncQueue[...]).Start.func1
> 	go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queuebatch/async_queue.go:47
> 2025-04-18T10:45:21.860-0500	info	Metrics	{"resource metrics": 1, "metrics": 4, "data points": 6}
> 2025-04-18T10:45:21.878-0500	error	internal/queue_sender.go:56	Exporting failed. Dropping data.	{"error": "insert histogram metrics failed: ERROR: improper qualified name (too many dotted names): otel.http.server.duration (SQLSTATE 42601)", "dropped_items": 6}
> 

Seems like a bug in metrics exported, are you using the metrics exporter branch that @rukins  is working on?

**Comment by rukins** [comment]
@clarencebishop please share the collector config you are using

**Comment by clarencebishop** [comment]
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  postgres:
  debug:

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters:
        - debug
        - postgres
    traces:
      receivers: [otlp]
      exporters:
        - debug
        - postgres
    metrics:
      receivers: [otlp]
      exporters:
        - debug
        - postgres

NOTE: I had to change postgresexporter to postgres for the exporter name

**Comment by clarencebishop** [comment]
Also, I am not seeing any logs or traces written to the otellogs and oteltraces table taht was created by the collector.

**Comment by rukins** [comment]
you haven't specified any database config, does it match defaults?

**Comment by clarencebishop** [comment]
I had to delete the database config information and use the defaults because of errors. It is using the default "otel" name for the database and schema. I can see that the collector is creating these objects.

**Comment by rukins** [comment]
do you have `_attributes_mappings` table created in your db?

**Comment by clarencebishop** [comment]
No, I did not see this table created in the otel database.

**Comment by rukins** [comment]
hmm, are you sure you are using the version from #2 ?

**Comment by clarencebishop** [comment]
I think so because I see all the newly added exporter_metrics.go file. Is there anyway to check that I am using the most current version of your work?

**Comment by clarencebishop** [comment]
I can see all of the metrics golang files in the internal directory.

**Comment by clarencebishop** [comment]
I can see the logs and traces in the respective tables. I was looking in the postgres database before instead of the otel database.

**Comment by clarencebishop** [comment]
Here is my builder-config yaml file:

dist:
  name: otellocalcol
  description: OpenTelemetry Collector Local for tests.
  version: 1.0.0
  output_path: ./cmd/otellocalcol

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.124.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.124.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.124.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.124.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.124.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.124.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.124.0
  - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.124.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.124.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.124.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.124.0

  - gomod: github.com/destrex271/postgresexporter v0.124.0
    path: "./exporter/postgresexporter" # if you have repo locally

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.28.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.28.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.28.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.28.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.28.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.124.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckv2extension v0.124.0

**Comment by rukins** [comment]
> Hi. I have sucessfully built the postgres exporter but I am getting the following error when my application creates a metric that the collector receives:
> 
> go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewQueueSender.func1 go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queue_sender.go:56 go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*disabledBatcher[...]).Consume go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queuebatch/disabled_batcher.go:22 go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*asyncQueue[...]).Start.func1 go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queuebatch/async_queue.go:47 2025-04-18T10:45:21.860-0500 info Metrics {"resource metrics": 1, "metrics": 4, "data points": 6} 2025-04-18T10:45:21.878-0500 error internal/queue_sender.go:56 Exporting failed. Dropping data. {"error": "insert histogram metrics failed: ERROR: improper qualified name (too many dotted names): otel.http.server.duration (SQLSTATE 42601)", "dropped_items": 6}

ah, I think I found the bug, yeah, will fix it now

**Comment by rukins** [comment]
> No, I did not see this table created in the otel database.

but, this table should have been created when you first run your collector

**Comment by clarencebishop** [comment]
The only objects created in the otel database are the following tables:
otellogs
oteltraces
oteltraces_trace_id_ts

And a materialized view:
oteltraces_trace_id_ts_mv

**Comment by rukins** [comment]
> > Hi. I have sucessfully built the postgres exporter but I am getting the following error when my application creates a metric that the collector receives:
> > go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewQueueSender.func1 go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queue_sender.go:56 go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*disabledBatcher[...]).Consume go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queuebatch/disabled_batcher.go:22 go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*asyncQueue[...]).Start.func1 go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queuebatch/async_queue.go:47 2025-04-18T10:45:21.860-0500 info Metrics {"resource metrics": 1, "metrics": 4, "data points": 6} 2025-04-18T10:45:21.878-0500 error internal/queue_sender.go:56 Exporting failed. Dropping data. {"error": "insert histogram metrics failed: ERROR: improper qualified name (too many dotted names): otel.http.server.duration (SQLSTATE 42601)", "dropped_items": 6}
> 
> ah, I think I found the bug, yeah, will fix it now

the bug is fixed, please pull new version and test it again

**Comment by rukins** [comment]
> The only objects created in the otel database are the following tables: otellogs oteltraces oteltraces_trace_id_ts
> 
> And a materialized view: oteltraces_trace_id_ts_mv

maybe that is because you disabled the metrics?🤔

**Comment by clarencebishop** [comment]
what is the git command I should use to get your latest updates? I want to make sure I am doing this correwctly.

**Comment by clarencebishop** [comment]
The metrics are no longer disabled and I still do not see the attributes table you mentioned.

**Comment by clarencebishop** [comment]
I have downloaded the code from the link above and rebuild the collector. It no longer generates the error that I was seeing before but I still do not see any metrics being collected. And I still do not see the _attributes_mappings table in the otel database.

**Comment by rukins** [comment]
the metrics is collected into `otel` schema by default, do you have it? this schema should have been auto created, as well

**Comment by clarencebishop** [comment]
I do not see an otel schema. The tables are being created in the public schema of the otel database.

**Comment by clarencebishop** [comment]
Do I need to manually create the otel schema?

**Comment by rukins** [comment]
> Do I need to manually create the otel schema?

no, it's created automatically

**Comment by clarencebishop** [comment]
When I use pgadmin to look atthe database objects. Under the otel database, the only schema showing is the public one. But when I try to manually create the otel schema, it says it already exist but still does not show it.

**Comment by rukins** [comment]
really weird :(
if it exists, maybe you just didn't reload the db?

**Comment by clarencebishop** [comment]
I have removed the otel database, manually recreated and re-ran the collector. I still do not see the otel schema under the Schema dropdown in pgadmin even though pgadmin tells me it exists when I tried to manually create it.

Where is the create_schema attribute set so I can check to make sure it is set to true?

**Comment by rukins** [comment]
your collector config should look similar to

```yaml
exporters:
        debug: {}
          # verbosity: detailed
        postgres:
          database:
            type: postgresql
            host: localhost
            port: 5432
            username: postgres
            password: postgres
            database: wabb
            schema: otel
          create_schema: true
```

**Comment by clarencebishop** [comment]
Here is my updated collector config file:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  postgres:
    database:
      type: postgresql
      host: localhost
      port: 5432
      username: postgres
      password: postgres
      database: otel
      schema: otel
    create_schema: true
  debug:

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters:
        - debug
        - postgres
    traces:
      receivers: [otlp]
      exporters:
        - debug
        - postgres
    metrics:
      receivers: [otlp]
      exporters:
        - debug
        - postgres

**Comment by clarencebishop** [comment]
The schema is being created because I can see it when use the \dn psql command although pgadmin does not show it. I do notice that there are no access permissions on the otel schema when I check it in psql.

Could this be the issue?

**Comment by rukins** [comment]
the config looks good

can you also set this and share your logs
```yaml
debug:
  verbosity: detailed
```

**Comment by clarencebishop** [comment]
The owner of the otel schema is postgres. Also the otel* tables are being created in the public schema and not the otel schema.

**Comment by clarencebishop** [comment]
Here is is the debug output:

2025-04-18T13:17:34.442-0500	info	service@v0.124.0/service.go:289	Everything is ready. Begin running and processing data.
2025-04-18T13:17:46.414-0500	info	Traces	{"resource spans": 1, "spans": 4}
2025-04-18T13:17:46.415-0500	info	ResourceSpans #0
Resource SchemaURL:
Resource attributes:
     -> telemetry.sdk.language: Str(python)
     -> telemetry.sdk.name: Str(opentelemetry)
     -> telemetry.sdk.version: Str(1.32.0)
     -> net.host.name: Str(WFWY062QTN.tld)
     -> net.host.ip: Str(143.244.220.150)
     -> service.name: Str(shopper)
     -> service.version: Str(0.1.2)
ScopeSpans #0
ScopeSpans SchemaURL:
InstrumentationScope shopper 0.1.2
Span #0
    Trace ID       : 697820d4272ce1b77b8a05f1e82bccbd
    Parent ID      : fdb748618ee173fb
    ID             : a03b9ba2159a4686
    Name           : web request
    Kind           : Client
    Start time     : 2025-04-18 18:17:46.347914 +0000 UTC
    End time       : 2025-04-18 18:17:46.386649 +0000 UTC
    Status code    : Ok
    Status message :
Attributes:
     -> http.method: Str(GET)
     -> http.flavor: Str(1.1)
     -> http.url: Str(http://localhost:5000/products)
     -> net.peer.ip: Str(127.0.0.1)
     -> http.status_code: Int(200)
Events:
SpanEvent #0
     -> Name: about to send a request
     -> Timestamp: 2025-04-18 18:17:46.347949 +0000 UTC
     -> DroppedAttributesCount: 0
SpanEvent #1
     -> Name: request sent
     -> Timestamp: 1970-01-01 00:00:00 +0000 UTC
     -> DroppedAttributesCount: 0
     -> Attributes::
          -> url: Str(http://localhost:5000/products)
Span #1
    Trace ID       : 697820d4272ce1b77b8a05f1e82bccbd
    Parent ID      : fdb748618ee173fb
    ID             : b5a551615d5ba6d2
    Name           : add item to cart
    Kind           : Internal
    Start time     : 2025-04-18 18:17:46.386703 +0000 UTC
    End time       : 2025-04-18 18:17:46.386722 +0000 UTC
    Status code    : Unset
    Status message :
Attributes:
     -> item: Str(orange)
     -> quantity: Int(5)
Span #2
    Trace ID       : 697820d4272ce1b77b8a05f1e82bccbd
    Parent ID      : bb00a0e3e72c7413
    ID             : fdb748618ee173fb
    Name           : browse
    Kind           : Internal
    Start time     : 2025-04-18 18:17:46.347864 +0000 UTC
    End time       : 2025-04-18 18:17:46.38676 +0000 UTC
    Status code    : Unset
    Status message :
Span #3
    Trace ID       : 697820d4272ce1b77b8a05f1e82bccbd
    Parent ID      :
    ID             : bb00a0e3e72c7413
    Name           : visit store
    Kind           : Internal
    Start time     : 2025-04-18 18:17:46.347829 +0000 UTC
    End time       : 2025-04-18 18:17:46.386766 +0000 UTC
    Status code    : Unset
    Status message :

2025-04-18T13:17:48.468-0500	info	Traces	{"resource spans": 1, "spans": 1}
2025-04-18T13:17:48.468-0500	info	ResourceSpans #0
Resource SchemaURL:
Resource attributes:
     -> telemetry.sdk.language: Str(python)
     -> telemetry.sdk.name: Str(opentelemetry)
     -> telemetry.sdk.version: Str(1.32.0)
     -> net.host.name: Str(WFWY062QTN.tld)
     -> net.host.ip: Str(143.244.220.150)
     -> service.name: Str(legacy-inventory)
     -> service.version: Str(0.9.1)
ScopeSpans #0
ScopeSpans SchemaURL:
InstrumentationScope legacy-inventory 0.9.1
Span #0
    Trace ID       : 697820d4272ce1b77b8a05f1e82bccbd
    Parent ID      : 690ceaa50885f6b6
    ID             : f5377280a358aa19
    Name           : /inventory
    Kind           : Server
    Start time     : 2025-04-18 18:17:46.36943 +0000 UTC
    End time       : 2025-04-18 18:17:46.370325 +0000 UTC
    Status code    : Unset
    Status message :
Attributes:
     -> http.flavor: Str(HTTP/1.1)
     -> http.method: Str(GET)
     -> http.user_agent: Str(python-requests/2.32.3)
     -> http.host: Str(localhost:5001)
     -> http.scheme: Str(http)
     -> http.target: Str(/inventory)
     -> http.client_ip: Str(127.0.0.1)

**Comment by rukins** [comment]
okay, give me time to figure out the issue

**Comment by clarencebishop** [comment]
Just some more information:

I can see the otel schema and the _attributes_mappings table but the otellogs and oteltraces tables are being created in the public schema. Is this correct behaviour?

Also, the _attributes_mappings table is empty.

**Comment by clarencebishop** [comment]
Which table should the metrics be in and which schema?

I remember reading some comments in the code that said metrics would be stored in their own tables for performance reasons.

**Comment by rukins** [comment]
> Which table should the metrics be in and which schema?
> 
> I remember reading some comments in the code that said metrics would be stored in their own tables for performance reasons.

Yeah, each metric has its own table.
I guess, you have no metrics collected yet

**Comment by clarencebishop** [comment]
My driver is generating counter and guage metrics but they are not being collected by the collector. When i use the ConsoleMetricExporter in my driver program I can see the metrics displayed on the console.

**Comment by clarencebishop** [comment]
I am now seeing rows in the otel._attributes_mappings table but I do not see any tables that contain the actual metric data.

**Comment by clarencebishop** [comment]
And I am seeing the following debug output:

HistogramDataPoints #0
StartTimestamp: 2025-04-18 18:50:30.95371 +0000 UTC
Timestamp: 2025-04-18 19:01:26.854711 +0000 UTC
Count: 1
Sum: 30.477000
Min: 30.477000
Max: 30.477000
ExplicitBounds #0: 0.000000
ExplicitBounds #1: 5.000000
ExplicitBounds #2: 10.000000
ExplicitBounds #3: 25.000000
ExplicitBounds #4: 50.000000
ExplicitBounds #5: 75.000000
ExplicitBounds #6: 100.000000
ExplicitBounds #7: 250.000000
ExplicitBounds #8: 500.000000
ExplicitBounds #9: 750.000000
ExplicitBounds #10: 1000.000000
ExplicitBounds #11: 2500.000000
ExplicitBounds #12: 5000.000000
ExplicitBounds #13: 7500.000000
ExplicitBounds #14: 10000.000000
Buckets #0, Count: 0
Buckets #1, Count: 0
Buckets #2, Count: 0
Buckets #3, Count: 0
Buckets #4, Count: 1
Buckets #5, Count: 0
Buckets #6, Count: 0
Buckets #7, Count: 0
Buckets #8, Count: 0
Buckets #9, Count: 0
Buckets #10, Count: 0
Buckets #11, Count: 0
Buckets #12, Count: 0
Buckets #13, Count: 0
Buckets #14, Count: 0
Buckets #15, Count: 0

2025-04-18T14:01:26.892-0500	error	internal/queue_sender.go:56	Exporting failed. Dropping data.	{"error": "insert histogram metrics failed: ERROR: improper qualified name (too many dotted names): otel.http.server.duration (SQLSTATE 42601)", "dropped_items": 6}
go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewQueueSender.func1
	go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queue_sender.go:56
go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*disabledBatcher[...]).Consume
	go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queuebatch/disabled_batcher.go:22
go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*asyncQueue[...]).Start.func1
	go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queuebatch/async_queue.go:47

**Comment by destrex271** [comment]
> Just some more information:
> 
> I can see the otel schema and the _attributes_mappings table but the otellogs and oteltraces tables are being created in the public schema. Is this correct behaviour?
> 
> Also, the _attributes_mappings table is empty.

Yep, this is how the trace and log exporters have been written. Mostly I tried to follow the way exporters were implemented for ClickHouse(https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/clickhouseexporter)

**Comment by rukins** [comment]
@clarencebishop `ERROR: improper qualified name (too many dotted names): otel.http.server.duration (SQLSTATE 42601)", "dropped_items": 6}` is caused by non-standard table names, I fixed the bug in the latest commit, please make sure you are using the updated version

**Comment by clarencebishop** [comment]
What git command do I use to pull your latest changes? I tried git pull and it said there was no changes. Sent from my iPhoneOn Apr 19, 2025, at 9:39 AM, Sergey ***@***.***> wrote:﻿
  @clarencebishop ERROR: improper qualified name (too many dotted names): otel.http.server.duration (SQLSTATE 42601)", "dropped_items": 6} is caused by non-standard table names, I fixed the bug in the latest commit, please make sure you are using the updated version—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>



rukins left a comment (destrex271/postgresexporter#1)
@clarencebishop ERROR: improper qualified name (too many dotted names): otel.http.server.duration (SQLSTATE 42601)", "dropped_items": 6} is caused by non-standard table names, I fixed the bug in the latest commit, please make sure you are using the updated version

**Comment by rukins** [comment]
Can you check the lastest commit you have locally?

**Comment by clarencebishop** [comment]
Good morning. I did a git pull to get your latest changes and then rebuilt the collector. I am still getting the same error.

**Comment by clarencebishop** [comment]
I also did a git clonehttps://github.com/wabb-in/postgresexporter/tree/metrics-exporter as I did last week to get the updated changes rather than a git pull but when I rebuilt the collector it complained about the entries in the config file. here is my config file:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  postgresexporter:
    database:
      type: postgres
      host: localhost
      port: 5432
      username: postgres
      password: postgres
      database: otel
      schema: otel
    create_schema: true
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters:
        - debug
        - postgresexporter
    traces:
      receivers: [otlp]
      exporters:
        - debug
        - postgresexporter
    metrics:
      receivers: [otlp]
      exporters:
        - debug
        - postgresexporter

And here are the errors:

Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'exporters': error reading configuration for "postgresexporter": decoding failed due to the following error(s):

'database' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[database:otel host:localhost password:postgres port:5432 schema:otel type:postgres username:postgres]'
'' has invalid keys: create_schema
2025/04/21 08:00:58 collector server run finished with error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'exporters': error reading configuration for "postgresexporter": decoding failed due to the following error(s):

'database' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[database:otel host:localhost password:postgres port:5432 schema:otel type:postgres username:postgres]'
'' has invalid keys: create_schema

**Comment by clarencebishop** [comment]
I corrected database.type and now get the following errors:

Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'exporters': unknown type: "postgres" for id: "postgres" (valid values: [otlphttp prometheus postgresexporter debug nop otlp])
2025/04/21 08:46:38 collector server run finished with error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'exporters': unknown type: "postgres" for id: "postgres" (valid values: [otlphttp prometheus postgresexporter debug nop otlp]

It does not seem to recognize 'postgres' as a valid exporter name. Ir seems to want to use postgresexporter but that does not work either. When I change it ot that name, it complains about not supporting the 'metrics' signal.

**Comment by rukins** [comment]
That means that you don't use the version from https://github.com/wabb-in/postgresexporter/tree/metrics-exporter

**Comment by clarencebishop** [comment]
I went to the above link and copied the git path and did a git clone with the following command:

git clone https://github.com/wabb-in/postgresexporter.git

Then I rebuilt the collector and I am still getting the following errors:

Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'exporters': unknown type: "postgres" for id: "postgres" (valid values: [otlp otlphttp prometheus postgresexporter debug nop])
2025/04/21 09:03:31 collector server run finished with error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'exporters': unknown type: "postgres" for id: "postgres" (valid values: [otlp otlphttp prometheus postgresexporter debug nop])

**Comment by rukins** [comment]
Checkout to the `metrics-exporter` branch

**Comment by clarencebishop** [comment]
Can youplease give me the exact git command I should be using to do what you are asking?

**Comment by rukins** [comment]
If you have already cloned the repo, you can execute the command
```
git checkout metrics-exporter
```

**Comment by destrex271** [comment]
Hi @clarencebishop , I'll suggest that you wait for the PRs #4 and #2  to be merged in main.

If any bugs are encountered then, we can start a separate issue for this. IMO we have diverged significantly from the current scope of this issue(which was to add the feature)

**Comment by clarencebishop** [comment]
Okay. Thank you for all your help.Do you have a timeframe when those merges into main will be complete?

**Comment by destrex271** [comment]
> Okay. Thank you for all your help.Do you have a timeframe when those merges into main will be complete?

Yep, for metrics exporter we plan to get it merged within this week.

As far as support for other postgres flavors is concerned, that is unclear for now but we'll definitely track it via an issue.

**Comment by clarencebishop** [comment]
Again, thank you for all your help. I really appreciate it. I will delete the current cloned repo go back and start from scratch with the initial clone to get into a known state.

**Comment by destrex271** [comment]
Closed in #2 . @clarencebishop you can try out the exporter from main now. Feel free to raise any new issues if you find any bugs

**Comment by clarencebishop** [comment]
Quick question: Why did you choose to break out the key/value pairs of attributes into a max of 20 distinct attribute columns rather that storing them as a single JSON column?

**Comment by rukins** [comment]
> Quick question: Why did you choose to break out the key/value pairs of attributes into a max of 20 distinct attribute columns rather that storing them as a single JSON column?

@clarencebishop it's for performance reasons. I think, in the future we will make it configurable.
Also, you can always check what attributes your metric has by querying to `_attributes_mappings`.

by the way, did you get it work?

**Comment by clarencebishop** [comment]
Yes, I got it to work and I am now seeing all the different tables representing the different metrics I create.

My earlier question was asking why not implement the attributes as a JSON structure like is done with resource_attributes? It seems more straight forward and intuitive to me and you can still query against the JSON values.

**Comment by rukins** [comment]
> Yes, I got it to work and I am now seeing all the different tables representing the different metrics I create.
> 
> My earlier question was asking why not implement the attributes as a JSON structure like is done with resource_attributes? It seems more straight forward and intuitive to me and you can still query against the JSON values.

Glad you got it working!
As for `resource_attributes`, it seems to be used rarely, so we chose the json structure.
But, again, we decided on distinct columns for metric attributes (up to 20 for now) primarily for query performance and indexing efficiency, especially for high-throughput metric queries

**Comment by destrex271** [comment]
> Yes, I got it to work and I am now seeing all the different tables representing the different metrics I create.
> 
> My earlier question was asking why not implement the attributes as a JSON structure like is done with resource_attributes? It seems more straight forward and intuitive to me and you can still query against the JSON values.

No problem, we'll address this soon and make it pretty simple for generic usage.
